
stages:
  - build
  - tests
  - delivery

variables:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres

default:
   services:
     - postgres

Project install:
  stage: build
  image: python:3.11
  script:
    - python -m pip install --no-cache-dir poetry 
    - poetry config virtualenvs.create false
    - poetry install --no-interaction --no-ansi --no-root
    - cd source
    - cat >> .env << EOF 
        SECRET_KEY=django-insecure-&)4s^s@9m^-b-xl5bja*01_^g7zi)s(#t7&tr=o#_3sasx5_ck

        DB_NAME=postgres
        DB_USER=postgres
        DB_PASSWORD=postgres
        DB_HOST=postgres
        DB_PORT=5432

        ALLOWED_HOSTS=
        CSRF_TRUSTED_ORIGINS=
        DEBUG=True
        EOF

    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic
    - python manage.py check