stages:
  - test
  - build
  - release

variables:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres

default:
   services:
     - postgres


test_project:
  stage: test
  image: python:3.11
  script:
    - python -m pip install --no-cache-dir poetry 
    - poetry config virtualenvs.create false
    - poetry install --no-interaction --no-ansi --no-root
    - mv example.env .env
    - cd source
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py collectstatic
    - python manage.py test
  tags:
    - appTest


docker_build:
  stage: build
  image: docker:stable
  service:
    - docker:dind
  only:
    - main
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} .
    - docker push ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG}
  tags:
    - dockerBuild


docker_release:
  stage: build
  image: docker:stable
  service:
    - docker:dind
  only:
    - main
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker pull ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} 
    - docker tag ${CI_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_REF_SLUG} ${CI_REGISTRY}/${CI_PROJECT_NAME}:latest
    - docker push ${CI_REGISTRY}/${CI_PROJECT_NAME}:$latest
  when: maunual
  tags:
    - dockerRelease

