version: '3.8'

services:
  db_1:
    container_name: db_1
    ports:
      - "5433:5432"
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgres/data
    env_file:
      - .env
    environment:
        - POSTGRES_DB=${DB_NAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_USER=${DB_USER}

  web:
    container_name: progress
    build: ./
    command: gunicorn main_config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./source:/src/source
      - static_volume:/src/source/static
      - media_volume:/src/source/media
    expose:
      - 8000
    restart: always
    depends_on:
      - db_1
    environment:
      #- SECRET_KEY=${SECRET_KEY}
      #- DATABASE_URL=postgres://postgres:postgres@db_1:5432/postgres
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db_1:5432/postgres
    env_file: .env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/src/source/static
      - media_volume:/src/source/media
    ports: 
      - 1337:80
    depends_on: 
      - web

volumes:
  postgres:
  static_volume:
  media_volume: