name: Test on Push
on: 
  pull_request:
    branches:
      - main

jobs:
  test_job:
    name: Testing App
    runs-on: ubuntu-latest
    services:
      db_1:
        image: postgres:14.3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    steps:
      - name: Download Project
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --no-cache-dir poetry 
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root
      - name: Run Tests
        run: |
          mv example.env .env
          cd source
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test

