name: Test on Push
on:
  push:
    branches:
      - '**'
      - '!main' 

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test_job:
    if: github.ref != 'refs/heads/main'   
    name: Testing App
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    services:
      db_1:
        image: postgres:14.3
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres

    steps:
      - name: Download Project
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --no-cache-dir poetry 
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root
      - name: Run Tests
        run: |
          mv example.env .env
          cd source
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test

      - name: Check if Pull Request exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list -H ${{github.ref_name}} -B 'main' )
          if ((prs > 0)); then
              echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Meka Pull Request
        if: '!steps.check.outputs.skip'
        run: gh pr create -H ${{github.ref_name}} -B main -t 'Merge ${{ github.sha }} from ${{github.ref}}' -b 'Generated by CI'




